// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Xy8cdyciRA6Z0_AKMQRRrQL2KsmZcAk',
    appId: '1:719953955625:web:22b2c54901516535d8c538',
    messagingSenderId: '719953955625',
    projectId: 'sportapp-43',
    authDomain: 'sportapp-43.firebaseapp.com',
    storageBucket: 'sportapp-43.appspot.com',
    measurementId: 'G-2T52SJHMEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCJ_2GJ8T-8hRtY8Fm-Pr_Gregxjs4Uw',
    appId: '1:719953955625:android:e5b4d9e77cf9e4a2d8c538',
    messagingSenderId: '719953955625',
    projectId: 'sportapp-43',
    storageBucket: 'sportapp-43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm3tN611obv9Lnwjy_G8p8QFaz8-Bh-0o',
    appId: '1:719953955625:ios:de5130a8a778ab4dd8c538',
    messagingSenderId: '719953955625',
    projectId: 'sportapp-43',
    storageBucket: 'sportapp-43.appspot.com',
    iosBundleId: 'com.example.sportapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm3tN611obv9Lnwjy_G8p8QFaz8-Bh-0o',
    appId: '1:719953955625:ios:de5130a8a778ab4dd8c538',
    messagingSenderId: '719953955625',
    projectId: 'sportapp-43',
    storageBucket: 'sportapp-43.appspot.com',
    iosBundleId: 'com.example.sportapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Xy8cdyciRA6Z0_AKMQRRrQL2KsmZcAk',
    appId: '1:719953955625:web:66a99d45228b86bcd8c538',
    messagingSenderId: '719953955625',
    projectId: 'sportapp-43',
    authDomain: 'sportapp-43.firebaseapp.com',
    storageBucket: 'sportapp-43.appspot.com',
    measurementId: 'G-056L563FLQ',
  );

}